name: my-web
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: ${{ secrets.KNOW_HOST }}
      - uses: actions/checkout@v3
      - run: rsync -v -e . ${SERVER_USER}@${SERVER_HOST}:~/my-web/
        env:
          SERVER_USER : ${{ secrets.SERVER_USER }}
          SERVER_HOST : ${{ secrets.SERVER_HOST }}