name: my-web
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: ${{ secrets.KNOW_HOST }}
      - uses: actions/checkout@v3
      - run: ssh ${SERVERUSER}@${SERVER_HOST} ls
      - run: ls