name: my-web
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: ${{ secrets.KNOW_HOST }}
      - uses: actions/checkout@v3
      - run: rsync -avz --chown=github:www-data --chmod=Dg=rwx,Fg=rwx ./ ${SERVER_USER}@${SERVER_HOST}:~/my-web/
        env:
          SERVER_USER : ${{ secrets.SERVER_USER }}
          SERVER_HOST : ${{ secrets.SERVER_HOST }}
      - run: | 
          ssh ${SERVER_USER}@${SERVER_HOST} sudo rm -rf /var/www/html/*
        env:
          SERVER_USER : ${{ secrets.SERVER_USER }}
          SERVER_HOST : ${{ secrets.SERVER_HOST }}