name: my-web
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: ${{ secrets.KNOW_HOST }}
      - uses: actions/checkout@v3
      - run: echo ${{secrets.KEY}}
      - run: ssh ${SERVER_USER}@${SERVER_HOST} sudo ls
        env:
          SERVER_USER : ${{ secrets.SERVERUSER }}
          SERVER_HOST : ${{ secrets.SERVER_HOST }}
      - run: ls