name: my-web
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: ${{ secrets.KNOW_HOST }}
      - uses: actions/checkout@v3
      - run:  rsync -v -e * ${SERVERUSER}@${SERVER_HOST}:~/my-web